"""
codegen.py — Phase D: generate (and run) a real Dagster pipeline per upload.

For each ingest we emit an inspectable, standalone Dagster project under
generated/<run>/:
    pipeline.py     — Dagster assets: ensure_warehouse -> load_warehouse, + a
                      fk_integrity asset check; runnable with `python pipeline.py`
    schema.json     — the LLM-proposed star schema
    rows.json       — the cleaned source rows (so the script is self-contained)

build_and_run() writes those files, imports the generated module, and materializes
it on the shared compact-dagster instance, returning the run summary + the code text.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re

import dagster_pipeline  # shared INSTANCE
import db

GEN_ROOT = os.path.join(os.path.dirname(__file__), "generated")

_TEMPLATE = '''"""AUTO-GENERATED by Pipeline Studio — Dagster pipeline for {title}.
Loads the cleaned source into the canonical star schema, FK-safe.
Run standalone:  python pipeline.py
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # reach backend modules
import db
from dagster import (asset, asset_check, AssetCheckResult, MaterializeResult,
                     TableColumn, TableSchema, Definitions, materialize)

HERE = os.path.dirname(os.path.abspath(__file__))
SCHEMA = json.load(open(os.path.join(HERE, "schema.json"), encoding="utf-8"))
ROWS = json.load(open(os.path.join(HERE, "rows.json"), encoding="utf-8"))
UPLOAD_ID = "{upload_id}"  # tags fact rows so re-running this pipeline is idempotent

TABLES = {{t["table"]: t for t in (SCHEMA["dimensions"] + SCHEMA["facts"])}}


def _table_schema(table):
    cols = TABLES[table]["columns"]
    return TableSchema(columns=[TableColumn(name=c["name"], type=c["type"]) for c in cols])


@asset(description="Create/extend the target warehouse tables (FK-safe DDL).")
def ensure_warehouse():
    res = db.ensure_tables(SCHEMA)
    return MaterializeResult(metadata={{
        "created": ", ".join(res["created"]) or "none",
        "altered": ", ".join(res["altered"]) or "none",
        "reused": ", ".join(res["reused"]) or "none",
    }})


@asset(deps=[ensure_warehouse],
       description="Upsert dimensions on their natural key, then insert FK-resolved facts.")
def load_warehouse():
    rep = db.load(SCHEMA, ROWS, UPLOAD_ID)
    md = {{}}
    for t, n in {{**rep["dimensions"], **rep["facts"]}}.items():
        if n is not None:
            md["rows__" + t] = n
    md["fk_unresolved"] = rep["fk_unresolved"]
    for fct in SCHEMA["facts"]:
        md["dagster/column_schema"] = _table_schema(fct["table"])
        break
    return MaterializeResult(metadata=md)


@asset_check(asset=load_warehouse, description="No orphan FK rows in the warehouse.")
def fk_integrity():
    orphans = db.fk_orphans()
    return AssetCheckResult(passed=(orphans == 0), metadata={{"orphan_rows": orphans}})


defs = Definitions(assets=[ensure_warehouse, load_warehouse], asset_checks=[fk_integrity])


def run(instance=None):
    return materialize([ensure_warehouse, load_warehouse, fk_integrity], instance=instance)


if __name__ == "__main__":
    r = run()
    print("pipeline run success:", r.success)
'''


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(s).lower()).strip("_") or "run"


def generate(schema: dict, rows_by_sheet: dict, title: str, run_id: str) -> dict:
    """Write the generated Dagster project to disk; return paths + the code text."""
    out_dir = os.path.join(GEN_ROOT, _slug(run_id))
    os.makedirs(out_dir, exist_ok=True)
    clean_schema = {k: v for k, v in schema.items() if not k.startswith("_")}
    with open(os.path.join(out_dir, "schema.json"), "w", encoding="utf-8") as f:
        json.dump(clean_schema, f, indent=2)
    with open(os.path.join(out_dir, "rows.json"), "w", encoding="utf-8") as f:
        json.dump(rows_by_sheet, f, default=str)
    code = _TEMPLATE.format(title=title, upload_id=run_id)
    path = os.path.join(out_dir, "pipeline.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write(code)
    return {"dir": out_dir, "pipeline_path": path, "code": code}


def build_and_run(schema: dict, rows_by_sheet: dict, title: str, run_id: str) -> dict:
    """Generate the pipeline, import it, and materialize it on the shared instance."""
    gen = generate(schema, rows_by_sheet, title, run_id)
    spec = importlib.util.spec_from_file_location(f"gen_{_slug(run_id)}", gen["pipeline_path"])
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    result = mod.run(instance=dagster_pipeline.INSTANCE)

    assets = []
    for ev in result.get_asset_materialization_events():
        mat = ev.event_specific_data.materialization
        assets.append({"asset": mat.asset_key.to_user_string(),
                       "metadata": {k: dagster_pipeline._meta_value(v) for k, v in mat.metadata.items()}})
    checks = [{"name": c.check_name, "passed": c.passed,
               "metadata": {k: dagster_pipeline._meta_value(v) for k, v in (c.metadata or {}).items()}}
              for c in result.get_asset_check_evaluations()]
    return {
        "success": result.success,
        "runId": result.run_id,
        "assets": assets,
        "checks": checks,
        "generatedCode": gen["code"],
        "generatedPath": os.path.relpath(gen["pipeline_path"], os.path.dirname(__file__)),
    }
